# Generated by Django 4.2 on 2023-04-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexpay_forexapp', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
