# Generated by Django 4.2 on 2023-04-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexpay_forexapp', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
