# Generated by Django 4.2 on 2023-05-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexpay_forexapp', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAccount',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
